In [4]:
from pprint import pprint

import numpy as np
import pandas as pd
from datasets import id_map, load_dataset, split_data
from linear_models import wrap
from sklearn.feature_selection import mutual_info_regression
from sklearn.isotonic import IsotonicRegression
from sklearn.linear_model import (
    ARDRegression,
    BayesianRidge,
    Lasso,
    LassoCV,
    LinearRegression,
    Ridge,
    RidgeCV,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import QuantileTransformer, RobustScaler, StandardScaler
from tqdm.auto import tqdm
from wrappers import BFS, RFS, RobustRegressor


In [5]:
pprint(id_map, sort_dicts=False)


{'student_performance': 320,
 'concrete': 165,
 'computer_hardware': 29,
 'kidney_disease': 857,
 'fertility': 244,
 'algerian_forest_fires': 547,
 'airfoil_self_noise': 291,
 'istanbul_stock_exchange': 247}


In [6]:
X, y = load_dataset("concrete")
print(X[:5])
print(y[:5])


[[ 540.     0.     0.   162.     2.5 1040.   676.    28. ]
 [ 540.     0.     0.   162.     2.5 1055.   676.    28. ]
 [ 332.5  142.5    0.   228.     0.   932.   594.   270. ]
 [ 332.5  142.5    0.   228.     0.   932.   594.   365. ]
 [ 198.6  132.4    0.   192.     0.   978.4  825.5  360. ]]
[2.6454072  1.5614213  0.2666269  0.31334004 0.50797844]


In [8]:
players = {
    # Classical methods
    # "LinearRegression": lambda x, _: wrap(LinearRegression()),
    "Ridge(1/(2n))": lambda x, _: wrap(Ridge(1 / (2 * len(x)))),
    "Isotonic(Ridge)": lambda x, _: wrap(Ridge(1 / (2 * len(x))), isotonic=True),
    # "RidgeCV(cv=10)": lambda x, _: wrap(
    #     RidgeCV(alphas=10 ** np.linspace(-4, 2, 20), cv=10)
    # ),
    # "LassoCV(cv=10)": lambda x, _: wrap(LassoCV(cv=10)),
    "ARDRegression": lambda x, _: wrap(ARDRegression()),
    "Isotonic(ARDRegression)": lambda x, _: wrap(ARDRegression(), isotonic=True),
    # Modifications
    # "Ridge": lambda x, _: wrap(Ridge(1 / (2 * len(x))), feats="id", outliers="id"),
    # "Ridge+BFS": lambda x, _: wrap(Ridge(1 / (2 * len(x))), feats="bfs", outliers="id"),
    # # "Ridge+RFS": lambda x, _: wrap(Ridge(1 / (2 * len(x))), feats="rfs", outliers="id"),
    # "Ridge+Robust": lambda x, _: wrap(
    #     Ridge(1 / (2 * len(x))), feats="id", outliers="robust"
    # ),
    # "Ridge+BFS+Robust": lambda x, _: wrap(
    #     Ridge(1 / (2 * len(x))), feats="bfs", outliers="robust"
    # ),
    # "ARDRegression+Robust": lambda x, _: wrap(
    #     ARDRegression(), feats="id", outliers="robust"
    # ),
    # "Ridge+RFS+Robust": lambda x, _: wrap(
    #     Ridge(1 / (2 * len(x))), feats="rfs", outliers="robust"
    # ),
    # "BFS(add_singles=True)": lambda x, _: BFS(
    #     wrap(Ridge(1 / (2 * len(x)))), add_singles=True
    # ),
    "BFS(add_singles=False)": lambda x, _: BFS(
        wrap(Lasso(1 / (2 * len(x)))), add_singles=False
    ),
    "Isotonic(BFS(add_singles=False))": lambda x, _: wrap(
        BFS(Lasso(1 / (2 * len(x))), add_singles=False),
        isotonic=True,
    ),
    # "BFS(add_singles=True, final=lasso_cv)": lambda x, _: BFS(
    #     wrap(Ridge(1 / (2 * len(x)))), add_singles=True, final="lasso_cv"
    # ),
    "BFS(add_singles=False, final=lasso_cv)": lambda x, _: BFS(
        wrap(Lasso(1 / (2 * len(x)))), add_singles=False, final="lasso_cv"
    ),
    # "BFS(add_singles=True, final=lasso)": lambda x, _: BFS(
    #     wrap(Ridge(1 / (2 * len(x)))), add_singles=True, final="lasso"
    # ),
    "BFS(add_singles=False, final=lasso)": lambda x, _: BFS(
        wrap(Lasso(1 / (2 * len(x)))), add_singles=False, final="lasso"
    ),
}

model_names = list(players.keys())

X, y = load_dataset("concrete")
# X, y = load_dataset("student_performance")

results = []
n_runs = 40
for run in tqdm(range(n_runs)):
    X_train, y_train, X_test, y_test = split_data(
        X, y, test_size=0.5, bad_features=False
    )
    models = [players[name](X_train, y_train) for name in model_names]

    for i, (name, model) in enumerate(zip(model_names, models)):
        model.fit(X_train, y_train)
        train_pred = model.predict(X_train)
        test_pred = model.predict(X_test)
        train_mse = np.square(train_pred - y_train).mean()
        test_mse = np.square(test_pred - y_test).mean()
        results.append(
            {"Model": name, "Train MSE": train_mse, "Test MSE": test_mse, "Run": run}
        )

df_all = pd.DataFrame(results)
df = (
    df_all.groupby("Model")
    .agg(
        Train_MSE_mean=("Train MSE", "mean"),
        Train_MSE_std=("Train MSE", "std"),
        Test_MSE_mean=("Test MSE", "mean"),
        Test_MSE_std=("Test MSE", "std"),
    )
    .reset_index()
)

df["Train MSE"] = df.apply(
    lambda x: f"{x['Train_MSE_mean']:.4f} ± {x['Train_MSE_std']:.4f}", axis=1
)
df["Test MSE"] = df.apply(
    lambda x: f"{x['Test_MSE_mean']:.4f} ± {x['Test_MSE_std']:.4f}", axis=1
)
df = df[["Model", "Train MSE", "Test MSE"]]
print(df.sort_values(by="Test MSE"))


100%|██████████| 40/40 [00:07<00:00,  5.24it/s]

                                    Model        Train MSE         Test MSE
6                         Isotonic(Ridge)  0.3222 ± 0.0168  0.3861 ± 0.0186
5        Isotonic(BFS(add_singles=False))  0.3237 ± 0.0173  0.3869 ± 0.0170
4                 Isotonic(ARDRegression)  0.3275 ± 0.0175  0.3885 ± 0.0151
1                  BFS(add_singles=False)  0.3787 ± 0.0172  0.4000 ± 0.0176
2     BFS(add_singles=False, final=lasso)  0.3790 ± 0.0172  0.4006 ± 0.0177
3  BFS(add_singles=False, final=lasso_cv)  0.3807 ± 0.0172  0.4014 ± 0.0171
0                           ARDRegression  0.3785 ± 0.0175  0.4016 ± 0.0189
7                           Ridge(1/(2n))  0.3768 ± 0.0175  0.4017 ± 0.0192


In [4]:
import time

from sklearn.linear_model import LinearRegression
from wrappers import BFS

# Benchmark fitting time for BFS with different final estimators
X_bench, y_bench = X_train.copy(), y_train.copy()
base_estimator = LinearRegression()
n_runs = 5

# BFS with ard
with_single_times = []
without_singles_times = []
for _ in range(n_runs):
    start_time = time.time()
    with_singles = BFS(base_estimator, add_singles=True)
    with_singles.fit(X_bench, y_bench)
    with_single_times.append(time.time() - start_time)
    start_time = time.time()
    without_singles = BFS(base_estimator, add_singles=False)
    without_singles.fit(X_bench, y_bench)
    without_singles_times.append(time.time() - start_time)
with_single_time_mean = np.mean(with_single_times)
with_single_time_std = np.std(with_single_times)
without_singles_time_mean = np.mean(without_singles_times)
without_singles_time_std = np.std(without_singles_times)


print(
    f"BFS(add_singles=False) fitting time: {without_singles_time_mean:.4f} ± {without_singles_time_std:.4f} seconds"
)
print(
    f"BFS(add_singles=True) fitting time: {with_single_time_mean:.4f} ± {with_single_time_std:.4f} seconds"
)


BFS(add_singles=False) fitting time: 0.0194 ± 0.0016 seconds
BFS(add_singles=True) fitting time: 0.0208 ± 0.0005 seconds


In [5]:
np.set_printoptions(suppress=True, precision=6, floatmode="fixed")
for i in range(2, len(models)):
    name = model_names[i]
    meta_coef = models[i].meta_estimator_[1].coef_
    intercept = models[i].meta_estimator_[1].intercept_
    print(name, meta_coef / np.sum(meta_coef), np.sum(meta_coef), intercept)


AttributeError: 'Pipeline' object has no attribute 'meta_estimator_'

In [6]:
A = models[4]
B = models[6]


In [13]:
print(A[1].coef_)


[ 0.6939171   0.5198963   0.31041625 -0.20310733  0.11226537  0.00358856
  0.          0.42565832]


In [16]:
B.feature_indices_


[array([0]),
 array([0, 4]),
 array([0, 4, 7]),
 array([0, 4, 7, 3]),
 array([0, 4, 7, 3, 6]),
 array([0, 4, 7, 3, 6, 5]),
 array([0, 4, 7, 3, 6, 5, 1]),
 array([0, 4, 7, 3, 6, 5, 1, 2])]

In [24]:
# A[1].coef_
np.set_printoptions(suppress=True, precision=6, floatmode="fixed")

meta_coef = B.meta_estimator_[1].coef_
print(meta_coef / np.sum(meta_coef))
total_coef = np.zeros(X_train.shape[1])
for i, meta_w in enumerate(meta_coef):
    feats = B.feature_indices_[i]
    weights = B.estimators_[i][1].coef_
    total_coef[feats] += weights * meta_w
total_coef


[0.000000 0.009541 0.000000 0.000000 0.023721 0.129458 0.319179 0.518100]


array([ 0.476652,  0.316338,  0.155053, -0.219728,  0.126291, -0.042684,
       -0.090598,  0.349651])

In [7]:
def EDA(name):
    X, y = load_dataset(name)
    assert isinstance(X, np.ndarray) and isinstance(y, np.ndarray)
    n_samples, n_features = X.shape
    assert y.shape == (n_samples,)
    print(f"{n_samples} samples, {n_features} features")
    k = 10
    subset = np.random.choice(n_samples, k)
    for i in range(n_features):
        n_unique = len(np.unique(X[:, i]))
        mn, mx = np.min(X[:, i]), np.max(X[:, i])
        mean = np.mean(X[:, i])
        std = np.std(X[:, i])
        C = 8
        sample = [int(C * x) / C for x in sorted(X[subset, i].tolist())]
        correlation = np.corrcoef(X[:, i], y)[0, 1]
        mutual_info = mutual_info_regression(X[:, i].reshape(-1, 1), y)[0]
        print(
            f"#{i}: {mn:.2f}..({mean:.2f} ± {std:.2f})..{mx:.2f}, {n_unique} unique, {sample} | C={correlation:.2f}, MI={mutual_info:.2f}"
        )


In [ ]:
EDA("istanbul_stock_exchange")


536 samples, 8 features
#0: 0.00..(267.50 ± 154.73)..535.00, 536 unique, [6.0, 75.0, 108.0, 199.0, 366.0, 433.0, 444.0, 506.0, 506.0, 525.0] | C=-0.03, MI=0.05
#1: -0.05..(0.00 ± 0.01)..0.07, 519 unique, [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | C=0.44, MI=0.09
#2: -0.05..(0.00 ± 0.01)..0.06, 527 unique, [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | C=0.60, MI=0.21
#3: -0.05..(0.00 ± 0.01)..0.05, 523 unique, [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | C=0.62, MI=0.26
#4: -0.05..(0.00 ± 0.01)..0.06, 503 unique, [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | C=0.26, MI=0.00
#5: -0.05..(0.00 ± 0.02)..0.06, 508 unique, [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | C=0.43, MI=0.06
#6: -0.05..(0.00 ± 0.01)..0.07, 532 unique, [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | C=0.66, MI=0.24
#7: -0.04..(0.00 ± 0.01)..0.05, 536 unique, [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] | C=0.60, MI=0.23
